"""users table creation

Revision ID: 30bfafb32426
Revises:
Create Date: 2025-07-05 12:20:55.370883

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "30bfafb32426"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    role_enum = sa.Enum("ADMIN", "ATTENDANT", "SECURITY", "POLICE", name="roleenum")

    op.create_table(
        "users",
        sa.Column("user_id", sa.String(length=20), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("email", sa.String(length=100), nullable=False),
        sa.Column("password", sa.String(length=100), nullable=False),
        sa.Column("role", role_enum, nullable=False),
        sa.Column("created_at", sa.DateTime, nullable=False),
        sa.PrimaryKeyConstraint("user_id"),
        sa.UniqueConstraint("email"),
        sa.UniqueConstraint("user_id"),
    )

    op.create_table(
        "attendants",
        sa.Column(
            "user_id",
            sa.String(length=20),
            sa.ForeignKey("users.user_id"),
            nullable=False,
        ),
        sa.Column("alloted_lot", sa.String(length=10), nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("attendants")
    op.drop_table("users")
    sa.Enum(name="roleenum").drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
